#!/bin/sh
cd /test_dir/glideinwms
if [ "$1" = "" ]; then
    branch="master"
else
    branch=$1
fi
git clean -f -d
git checkout master
git pull
git checkout "$branch"
cd /test_dir
. "$VIRTUAL_ENV"/bin/activate
exclude_file="/test_dir/slow_test_list"
failed=""
cd glideinwms/unittests
cd jobsub/test/server/unit_tests
for PY in  ./test_*.py; do
    grep "$PY" $exclude_file > /dev/null 2>&1 
    if [ $? -eq 0 ] ; then
        echo skipping "$PY", too slow
    else
        echo running: "$PY"
        python "$PY"
        if [ $? -ne 0 ]; then
            failed="$failed $PY"
        fi
    fi
done
if [ "$failed" = "" ]; then
    echo all tests passed
    exit 0
else
    echo "failed tests in $failed"
    exit 1
fi
    
