#!/bin/sh
cd "$TEST_DIR/$PROJECT"
if [ "$1" = "" ]; then
    branch="master"
else
    branch=$1
fi

thisbranch=$(git branch | grep '\*' | awk '{print $2}')

if [ "$thisbranch" != "$branch" ]; then
    echo "want to run $0 on $branch but $thisbranch is checked out"
    echo "set_test_env '$branch' must be run prior to this job"
    exit 1
fi


cd "$TEST_DIR"
. "$VIRTUAL_ENV"/bin/activate
branch_dir="$TEST_DIR"/output/$(echo "$branch"| sed -e 's/\//_/g')
mkdir -p  "$branch_dir/xml_reports"
./jobsub/test/scripts/run_unittests.sh -ac 2>&1 | tee "$branch_dir"/unit_test.log
mv ./jobsub/test/scripts/unittests-reports/* "$branch_dir/xml_reports"
mv ./htmlcov* "$branch_dir"
mv ./coverage.report.* "$branch_dir"
mv ./*.out "$branch_dir"
mv ./*.log "$branch_dir"
