#!/bin/sh
cd /jobsub_test/jobsub
if [ "$1" == "" ]; then
    branch="master"
else
    branch=$1
fi
git checkout $branch
cd test/scripts
for F in $(cat /jobsub_test/jenkins_scripts); do git checkout master $F; done
cd /jobsub_test
source $VIRTUAL_ENV/bin/activate
no_slash=output/$(echo $branch| sed -e 's/\//_/g')
mkdir -p $no_slash
./jobsub/test/scripts/run_pylint.sh 2>&1 | tee $no_slash/pylint.log
mv *.log $no_slash
