#!/bin/sh
cd "$TEST_DIR/$PROJECT"
if [ "$1" = "" ]; then
    branch="master"
else
    branch=$1
fi
git clean -f -d
git checkout master
git pull
git checkout "$branch"
cd $TEST_DIR/$PROJECT/test/scripts
for F in $(cat $TEST_DIR/jenkins_scripts); do
    git checkout master $F
done
